# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 01:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('nome', models.CharField(max_length=150, verbose_name='Modelo')),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'db_table': 'modelo',
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='ModeloInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('nome_input', models.CharField(max_length=150, verbose_name='Input')),
                ('tipo_input', models.IntegerField(choices=[(1, b'Integer'), (2, b'Decimal'), (3, b'String'), (4, b'Date'), (5, b'Text'), (6, b'Bool')], default=1, verbose_name='Tipo Input')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigat\xf3rio?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_input', to='gerador.Modelo', verbose_name='Modelo')),
            ],
            options={
                'db_table': 'modelo_input',
                'verbose_name': 'Modelo Input',
                'verbose_name_plural': 'Modelos Inputs',
            },
        ),
    ]
