# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0002_modeloinput_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloinput',
            options={'verbose_name': 'Modelo Input', 'verbose_name_plural': 'Inputs do Modelo'},
        ),
        migrations.AlterField(
            model_name='modeloinput',
            name='tipo_input',
            field=models.IntegerField(choices=[(1, b'Integer'), (2, b'Decimal'), (3, b'String'), (4, b'Date'), (5, b'Text'), (6, b'Bool'), (7, b'List')], default=1, verbose_name='Tipo Input'),
        ),
    ]
