<script src="<?php echo site_url('public/resources'); ?>/modelo/js/modelo.js"></script>

<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Modelos</h3>

                <div class="box-body" style="float: right">
                    <div class="form-group">
                        <button id="btn-novo"  href="<?php echo site_url('modelo/registro');?>" class="btn btn-primary">Novo</button>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form">
                <div class="box-body">
                    <div class="box-body">
                        <table id="grid-modelo" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Nome</th>
                                <th>Descrição</th>
                                <th>Ativo?</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
