<script src="<?php echo site_url('public/resources/modelo/js'); ?>/modelo.js"></script>

<div class="col-md-12">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Modelo</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal">
            <div class="box-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Nome do Modelo</label>

                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="nome_modelo" name="nome_modelo" value="" placeholder="Nome do Modelo">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Ativo?
                            </label>
                        </div>
                    </div>
                </div>
            </div>


            <div class="box-header">
                <h3 class="box-title">Descrição do Modelo
                </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body pad">
                <form>
                    <textarea id="editor1" name="editor1" rows="10" cols="80"></textarea>
                </form>
            </div>

            <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Obrigatório</th>
                        <th>Unique?</th>
                        <th>Ativo?</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td></td>
                        <td>Trident</td>
                        <td>Internet Explorer 4.0</td>
                        <td>Win 95+</td>
                        <td> 4</td>
                        <td>X</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="box-body">
                <div class="form-group">
                    <button type="button" class="btn btn-block btn-primary btn-lg">Enviar</button>
                </div>
            </div>

        </form>
    </div>
</div>