<div id="forgot-box" class="forgot-box widget-box no-border visible">
	<div class="widget-body">
		<div class="widget-main">
			<h4 class="header red lighter bigger">
				<i class="ace-icon fa fa-key"></i> Recuperar Senha
			</h4>
			<div class="space-6"></div>
			<p>Insira seu e-mail para receber sua senha</p>
			<form>
				<fieldset>
					<label class="block clearfix"> <span class="block input-icon input-icon-right"> <input type="email" class="form-control" placeholder="Email" /> <i class="ace-icon fa fa-envelope"></i>
					</span>
					</label>
					<div class="clearfix">
						<button type="button" class="width-35 pull-right btn btn-sm btn-danger">
							<i class="ace-icon fa fa-lightbulb-o"></i> <span class="bigger-110">Enviar!</span>
						</button>
					</div>
				</fieldset>
			</form>
		</div>
		<!-- /.widget-main -->
		<div class="toolbar center">
			<a href="<?php echo site_url("login"); ?>" data-target="#login-box" class="back-to-login-link"> Voltar ao login <i class="ace-icon fa fa-arrow-right"></i>
			</a>
		</div>
	</div>
	<!-- /.widget-body -->
</div>
<!-- /.forgot-box -->