<div class="position-relative">
    <div id="login-box" class="login-box visible widget-box no-border">
        <div class="widget-body">
            <div class="widget-main">
                <h4 class="header blue lighter bigger">
                    <i class="ace-icon fa fa-coffee green"></i> Insira seus dados de acesso.
                </h4>
                <div class="space-6"></div>
                <form id="frm" name="frm" method="post" action="<?php echo site_url("login/logar"); ?>">
                    <fieldset>
                        <label class="block clearfix"> <span class="block input-icon input-icon-right"> 
                        <input type="text" class="form-control" placeholder="E-mail" name="email" id="email"/> <i class="ace-icon fa fa-user"></i>
                        </span>
                        </label> <label class="block clearfix"> <span class="block input-icon input-icon-right"> 
                        <input type="password" class="form-control" placeholder="Password" name="senha" id="senha"/> <i class="ace-icon fa fa-lock"></i>
                        </span>
                        </label>
                        <div class="space"></div>
                        <div class="clearfix">
                            <label class="inline"> <input type="checkbox" class="ace" /> <span class="lbl"> Lembre-me</span>
                            </label>
                            <button id="enviar" type="submit" class="width-35 pull-right btn btn-sm btn-primary">
                                <i class="ace-icon fa fa-key"></i> <span class="bigger-110">Login</span>
                            </button>
                        </div>
                        <div class="space-4"></div>
                        <?php 
                            if (isset($error)) { ?>
                            <div class="clearfix">
                                <label class="inline"> <span class="lbl"> <?php echo $error; ?></span>
                                </label>
                            </div>
                            <?php }?>
                    </fieldset>
                </form>
                <div class="space-6"></div>
            </div>
            <!-- /.widget-main -->
            <div class="toolbar clearfix">
                <div>
                    <a href="<?php echo site_url("login/forgotpassword"); ?>" data-target="#forgot-box" class="forgot-password-link"> <i class="ace-icon fa fa-arrow-left"></i> Esqueci minha senha
                    </a>
                </div>
            </div>
        </div>
        <!-- /.widget-body -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.position-relative -->
